### ISSUE TITLE
Error building site, SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by aroly** [opera7133/tella#118]
Hello,

I'm trying to setup a nuw Hugo website with tella, and I get the following error when running `hugo server -D`:

```
$ hugo server -D
Start building sites … 
hugo v0.103.1+extended linux/amd64 BuildDate=unknown
Error: Error building site: POSTCSS: failed to transform "css/style.css" (text/css): /home/hugo/hugo/erasec/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hugo/hugo/erasec/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Built in 1918 ms

```

Hugo server is:

```
$ hugo version
hugo v0.103.1+extended linux/amd64 BuildDate=unknown
```

Did I made a mistake somewhere ? The SyntaxError makes me think the problem is not on my side, but you never know... 

Thanks in advance,

A.

**Comment by opera7133** [comment]
My environment has no problems, so you may be making a mistake in setup or somewhere else.
Try deleting and re-installing dependencies and node_modules, updating packages, etc.
If it does not work by any means, try reinserting it according to the [README](https://github.com/opera7133/tella#install-dependencies).

**Comment by hunkjun** [comment]
SyntaxError: Unexpected token '.'：这个错误提示是因为你的JavaScript代码中使用了可选链操作符（?.），而你的Node.js版本可能不支port这个特性。可选链在Node.js 14中被引入，所以如果你的Node.js版本低于14，你会遇到这个错误。你可以通过升级你的Node.js版本解决这个问题。
